# Generated by Django 5.0.4 on 2024-05-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("price", models.IntegerField()),
                ("lifetime_months", models.IntegerField()),
                ("channel_email", models.BooleanField()),
                ("channel_phone", models.BooleanField()),
                ("reason_signup", models.BooleanField()),
                ("reason_support", models.BooleanField()),
                ("gender_female", models.BooleanField()),
                ("gender_male", models.BooleanField()),
                ("subscription_annual_subscription", models.BooleanField()),
                ("subscription_monthly_subscription", models.BooleanField()),
                ("signup_period_Morning", models.BooleanField()),
                ("signup_period_Night", models.BooleanField()),
                ("signup_period_Noon", models.BooleanField()),
                ("end_period_Morning", models.BooleanField()),
                ("end_period_Night", models.BooleanField()),
                ("end_period_Noon", models.BooleanField()),
            ],
        ),
    ]
