# Generated by Django 5.0.4 on 2024-05-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="mode_of_contact",
            field=models.CharField(max_length=50, verbose_name="Contact by"),
        ),
    ]
